obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_ctl.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_esd_protection.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_gesture.o
