obj-y				:= dma-mapping.o extable.o fault.o init.o \
				   copypage.o flush.o \
				   ioremap.o iomap.o mmap.o pgd.o mmu.o \
				   context.o pageattr.o #proc.o cache.o  
obj-$(CONFIG_HUGETLB_PAGE)	+= hugetlbpage.o
obj-$(CONFIG_ARM64_PTDUMP)	+= dump.o
